[package]
name = "actuate"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "actuate_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["macos-private-api", "tray-icon"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-store = "2"
tauri-plugin-stronghold = "2"
tauri-plugin-dialog = "2"
walkdir = "2.5.0"
glob = "0.3.3"
tauri-plugin-http = { version = "2", features = ["unsafe-headers"] }
arboard = "3.6.1"
diffy = "0.5.0"
time = { version = "0.3.53", features = ["formatting"] }
image = { version = "0.25.10", features = ["png"], default-features = false }
base64 = "0.22.1"
tokio = { version = "1.52.3", features = ["sync", "time", "rt", "macros"] }
tauri-plugin-notification = "2.3.3"
tauri-plugin-sql = { version = "2.4.0", features = ["sqlite"] }

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-single-instance = "2"
tauri-plugin-window-state = "2"
tauri-plugin-global-shortcut = "2"

[target.'cfg(windows)'.dependencies]
uiautomation = "0.25.0"
windows = { version = "0.62.2", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging", "Win32_UI_Input_KeyboardAndMouse", "Win32_UI_HiDpi", "Win32_System_Threading", "Win32_System_ProcessStatus", "Win32_System_Diagnostics_ToolHelp", "Win32_System_Com", "Win32_System_Registry", "Win32_System_Environment", "Win32_UI_Accessibility"] }

[target.'cfg(target_os = "macos")'.dependencies]
block2 = "0.6"
mach2 = "0.6.0"
objc2 = "0.6.4"
objc2-app-kit = { version = "0.3.2", default-features = false, features = [
    "NSRunningApplication",
    "NSScreen",
    "NSWindow",
    "NSWorkspace",
    "block2",
    "libc",
] }
objc2-application-services = "0.3.2"
objc2-core-foundation = "0.3.2"
objc2-core-graphics = { version = "0.3.2", default-features = false, features = [
    "std",
    "CGWindow",
    "CGEvent",
    "CGEventSource",
    "CGEventTypes",
    "CGDirectDisplay",
    "CGRemoteOperation",
    "CGError",
] }
objc2-foundation = { version = "0.3.2", default-features = false, features = [
    "NSArray",
    "NSDictionary",
    "NSError",
    "NSObject",
    "NSString",
    "NSURL",
] }
plist = "1.10.0"

[target."cfg(unix)".dependencies]
libc = "0.2"

[features]
default = []
a11y-bench = []

[profile.dev.package.scrypt]
opt-level = 3
